// ─── Helix Calisthenics Library ───────────────────────────────────────────────
//
// Three purposes:
//   1. Bodyweight exercise progressions for every movement pattern —
//      feeds the pure calisthenics program generator and hybrid mode
//   2. Skill progression ladders — feeds the Calisthenics tab
//   3. Session structure guidelines — how to combine skill and volume work
//
// Sources:
// — EMG research: Harman et al. (2018) J Phys Fit Treatment Sports — pull-ups superior core activation vs pulldowns
// — EMG research: Edelburg (Wisconsin University thesis) — pull-up/chin-up significantly greater lat activation than lat pulldown
// — EMG research: PubMed PMID:24245055 — greater bicep and erector spinae in chin-ups vs lat pulldowns
// — Greasing the Groove methodology: Tsatsouline (The Naked Warrior, 2003); Häkkinen et al. (1988) — frequency > volume for skill
// — Progressive overload without weight: variation ladder, tempo, volume, load (vest/belt)
// — Session structure: skill first (fresh CNS), volume second — consistent across all credible calisthenics coaching
// — Planche biomechanics: torque analysis (tuck ~113 Nm, adv tuck ~136 Nm, straddle ~162 Nm, full ~183 Nm)
// — Pull-up progression: Invictus Fitness, Berg Movement, Heavyweight Calisthenics (public methodology)
// — Front lever: Berg Movement, Club Calisthenics, Breaking Muscle (public methodology)
// — Handstand: Calisthenics Association, Movement Athlete, PHD (public methodology)
// — Muscle-up: Maximum Potential Calisthenics, Heavyweight Calisthenics (public methodology)
// — Legs limitation: honest acknowledgment — calisthenics legs plateau faster than upper body (BetterMe research)

// ─── MOVEMENT PATTERN PROGRESSIONS ──────────────────────────────────────────
// Each pattern has exercises ordered from easiest → hardest.
// These slot into the same MOVEMENT_PATTERNS as movementLibrary.js.
// Pull-ups are PRIMARY for vertical pull — lat pulldown is a regression.

export const CALISTHENICS_PROGRESSIONS = {

  // ─── HORIZONTAL PUSH (Chest) ───────────────────────────────────────────────
  chest_horizontal_push: {
    label: 'Chest — Horizontal Push',
    muscles: ['Chest', 'Shoulders', 'Triceps'],
    progressions: [
      {
        id: 'wall_push_up',
        name: 'Wall push-up',
        level: 1,
        equipment: ['bodyweight'],
        sets: 3, reps: '10–15', rest: '60 sec',
        description: 'Hands on wall, body at an angle. The more upright you stand, the easier.',
        advance_standard: '3×15 with good form',
        muscles_primary: ['Chest', 'Shoulders', 'Triceps'],
        cues: ['Keep body in a straight line', 'Lower chest to wall, push away', 'Do not let hips sag'],
      },
      {
        id: 'incline_push_up',
        name: 'Incline push-up',
        level: 2,
        equipment: ['bodyweight'],
        sets: 3, reps: '10–15', rest: '60 sec',
        description: 'Hands elevated on a bench or step. Easier than floor, harder than wall.',
        advance_standard: '3×15 clean reps',
        cues: ['Straight line from head to heels', 'Touch chest to surface', 'Control the descent for 2 seconds'],
      },
      {
        id: 'push_up',
        name: 'Push-up',
        level: 3,
        equipment: ['bodyweight'],
        sets: 3, reps: '8–15', rest: '90 sec',
        description: 'The standard. Full ROM, chest touches floor, arms fully extended at top.',
        advance_standard: '3×15 strict reps with 2 sec descent',
        cues: [
          'Hands just outside shoulder width',
          'Elbows 45° from torso — not flared, not tucked',
          'Full dead hang at top — arms straight',
          'Chest TOUCHES floor, do not stop 5cm short',
          'Hollow body — core braced, glutes squeezed',
        ],
        research_note: 'Push-ups match bench press for hypertrophy when trained close to failure and volume is equated (PLOS One). The advantage of push-ups: forced hollow body tension develops core stability that bench press does not.',
      },
      {
        id: 'close_grip_push_up',
        name: 'Close-grip push-up',
        level: 3,
        equipment: ['bodyweight'],
        sets: 3, reps: '8–12', rest: '90 sec',
        description: 'Hands closer than shoulder width, emphasises triceps and inner chest.',
        advance_standard: '3×12 strict',
        cues: ['Hands directly under shoulders', 'Elbows travel back along your torso', 'More tricep feel than standard push-up'],
      },
      {
        id: 'wide_push_up',
        name: 'Wide push-up',
        level: 3,
        equipment: ['bodyweight'],
        sets: 3, reps: '8–12', rest: '90 sec',
        description: 'Hands 1.5–2× shoulder width. Greater chest stretch at the bottom.',
        advance_standard: '3×12 strict with chest to floor',
        cues: ['Elbows flare slightly more than standard', 'Greater pec stretch — use slower descent to feel it', 'Do not let elbows hyper-extend at top'],
      },
      {
        id: 'decline_push_up',
        name: 'Decline push-up',
        level: 4,
        equipment: ['bodyweight'],
        sets: 3, reps: '8–12', rest: '90 sec',
        description: 'Feet elevated on bench. More shoulder and upper chest emphasis.',
        advance_standard: '3×12 with feet on 60cm+ surface',
        cues: ['Feet on bench, hands on floor', 'Body stays in straight line — no hips piking', 'The higher your feet, the more shoulder emphasis'],
      },
      {
        id: 'diamond_push_up',
        name: 'Diamond push-up',
        level: 4,
        equipment: ['bodyweight'],
        sets: 3, reps: '6–10', rest: '90 sec',
        description: 'Hands form a diamond shape under chest. Heavy tricep emphasis.',
        advance_standard: '3×10 strict',
        cues: ['Index fingers and thumbs touching, forming a diamond', 'Elbows stay close to torso throughout', 'Very tricep dominant — use lower volume than standard push-up'],
      },
      {
        id: 'archer_push_up',
        name: 'Archer push-up',
        level: 5,
        equipment: ['bodyweight'],
        sets: 3, reps: '5–8 each side', rest: '2 min',
        description: 'One arm bent and doing the work, the other straight out to the side as a support. Transitional step toward one-arm push-up.',
        advance_standard: '3×8 each side with control',
        cues: [
          'Wide hand placement to start',
          'Shift weight to the working arm and bend that elbow',
          'Non-working arm stays straight — provides balance, not push',
          'Gradually reduce assistance from non-working arm over time',
        ],
      },
      {
        id: 'pike_push_up',
        name: 'Pike push-up',
        level: 5,
        equipment: ['bodyweight'],
        sets: 3, reps: '6–10', rest: '2 min',
        description: 'Hips high, forming an inverted V. Shifts load heavily onto shoulders — the gateway to handstand push-ups.',
        advance_standard: '3×10 strict, head almost to floor',
        cues: [
          'Start in downward dog position — hips as high as possible',
          'Lower your head TOWARD the floor between your hands',
          'Head should nearly touch — do not stop halfway',
          'Push back up by straightening arms',
          'The more upright your hips, the more shoulder dominant',
        ],
        research_note: 'Pike push-ups directly train the shoulder press strength needed for handstand push-ups. Required prerequisite before wall HSPU.',
      },
      {
        id: 'pseudo_planche_push_up',
        name: 'Pseudo planche push-up',
        level: 6,
        equipment: ['bodyweight'],
        sets: 3, reps: '5–8', rest: '2 min',
        description: 'Hands rotated outward, lean weight forward over hands. Trains the planche pushing strength and anterior deltoid.',
        advance_standard: '3×8 with significant forward lean',
        cues: [
          'Fingers pointing toward your hips (rotated outward)',
          'Lean bodyweight FORWARD so shoulders are in front of hands',
          'The more forward your lean, the harder and more planche-specific',
          'This is the primary planche strength builder besides the holds themselves',
        ],
        research_note: 'Directly transfers to planche skill. Progressively increase forward lean to simulate tuck → advanced tuck → full planche torque demands.',
      },
      {
        id: 'one_arm_push_up',
        name: 'One-arm push-up',
        level: 7,
        equipment: ['bodyweight'],
        sets: 3, reps: '3–6 each side', rest: '3 min',
        description: 'Full bodyweight on one arm. One of the highest-difficulty horizontal push exercises.',
        advance_standard: '3×5 each side with full ROM',
        cues: [
          'Wide foot stance for balance',
          'Non-working hand behind back or on thigh',
          'Resist the urge to rotate your torso — stay square',
          'Elbow of working arm tracks 45° from torso',
        ],
      },
    ],
  },

  // ─── VERTICAL PUSH (Shoulders) ─────────────────────────────────────────────
  shoulders_vertical_push: {
    label: 'Shoulders — Vertical Push',
    muscles: ['Shoulders', 'Triceps', 'Upper chest'],
    progressions: [
      {
        id: 'pike_push_up_vertical',
        name: 'Pike push-up',
        level: 1,
        equipment: ['bodyweight'],
        sets: 3, reps: '8–12', rest: '90 sec',
        description: 'Inverted V position, lower head toward floor. The foundation of overhead pressing in calisthenics.',
        advance_standard: '3×12 with head nearly touching floor',
        cues: ['Hips as high as possible', 'Head lowers BETWEEN hands, not outside them', 'Push through the full range'],
      },
      {
        id: 'elevated_pike_push_up',
        name: 'Elevated pike push-up',
        level: 2,
        equipment: ['bodyweight'],
        sets: 3, reps: '6–10', rest: '2 min',
        description: 'Feet on a bench or box, deepening the overhead angle and increasing shoulder load.',
        advance_standard: '3×10 with feet on 60cm surface',
        cues: ['Feet higher = more vertical = harder', 'Head tracks between hands', 'Fully extend at top'],
      },
      {
        id: 'wall_hspu',
        name: 'Wall handstand push-up',
        level: 3,
        equipment: ['bodyweight'],
        sets: 3, reps: '3–8', rest: '3 min',
        description: 'Kick up into a wall handstand, lower head to floor, press back up. A true vertical press at full bodyweight.',
        advance_standard: '3×8 with head touching floor each rep',
        prerequisite: 'Must hold a wall handstand for 60 seconds before starting',
        cues: [
          'Back against wall, hands shoulder-width apart',
          'Lower head to floor — do NOT stop 10cm short',
          'Head touches floor BETWEEN hands (slight triangle shape)',
          'Press back to full lockout',
          'Core stays braced — no banana back',
        ],
        research_note: 'EMG studies confirm the overhead vertical press position (handstand push-up) is the highest shoulder activation exercise in calisthenics. Equivalent to a barbell press at bodyweight.',
      },
      {
        id: 'wall_hspu_deficit',
        name: 'Deficit handstand push-up',
        level: 4,
        equipment: ['bodyweight'],
        sets: 3, reps: '3–6', rest: '3 min',
        description: 'Hands on parallettes or books, allowing head to drop BELOW hand level. Greater ROM, harder than wall HSPU.',
        advance_standard: '3×5 with full range of motion',
        cues: ['Parallettes or elevated surfaces for hands', 'Head drops BELOW hand level at the bottom', 'Straight line from wrists to hips throughout'],
      },
      {
        id: 'freestanding_hspu',
        name: 'Freestanding handstand push-up',
        level: 5,
        equipment: ['bodyweight'],
        sets: 3, reps: '1–5', rest: '4 min',
        description: 'Handstand push-up away from the wall. Adds balance demand to the strength requirement. One of the hardest calisthenics skills.',
        advance_standard: '3×3 controlled reps',
        prerequisite: 'Must hold a freestanding handstand for 30 seconds before attempting',
        cues: [
          'Start in freestanding handstand with balance',
          'Lower SLOWLY — much harder to control without wall',
          'Head between hands at the bottom',
          'Press to lockout and re-establish balance',
        ],
      },
    ],
  },

  // ─── VERTICAL PULL (Lats) ──────────────────────────────────────────────────
  // Pull-ups are PRIMARY. Lat pulldown is a regression, not an alternative.
  // Research: pull-up produces significantly greater rectus abdominis, bicep brachii,
  // and erector spinae activation than lat pulldown (Harman 2018, PMID:24245055, Edelburg).
  back_vertical_pull: {
    label: 'Back — Vertical Pull',
    muscles: ['Lats', 'Biceps', 'Core', 'Rear delts'],
    primary_note: 'Pull-ups are the gold standard. Lat pulldown is a regression for those who cannot yet do pull-ups — not a permanent alternative. Switch to pull-ups when you can do 5 strict reps.',
    progressions: [
      {
        id: 'dead_hang',
        name: 'Dead hang',
        level: 1,
        equipment: ['pullup_bar'],
        sets: 3, reps: '20–60 sec holds', rest: '60 sec',
        description: 'Hang from a bar at full arm extension. Builds grip, shoulder packing, and connective tissue.',
        advance_standard: '3×45 sec holds',
        cues: ['Arms fully extended — do not shrug', 'Squeeze the bar as hard as possible', 'Shoulders slightly back and down — not passive hang'],
      },
      {
        id: 'scapular_pull_up',
        name: 'Scapular pull-up',
        level: 1,
        equipment: ['pullup_bar'],
        sets: 3, reps: '8–12', rest: '60 sec',
        description: 'Dead hang, then pull shoulder blades DOWN without bending elbows. Teaches lat activation before full pull-up.',
        advance_standard: '3×12 with clear shoulder blade depression',
        cues: ['Arms stay STRAIGHT throughout', 'Pull your shoulder blades down toward your back pockets', 'Hold 1 second at the top of each rep'],
      },
      {
        id: 'negative_pull_up',
        name: 'Negative pull-up',
        level: 2,
        equipment: ['pullup_bar'],
        sets: 3, reps: '5–8', rest: '2 min',
        description: 'Jump or step to the top position, lower as slowly as possible (4–6 seconds). Eccentric strength is the fastest route to a full pull-up.',
        advance_standard: '3×5 with 5+ second descent',
        cues: [
          'Jump or use a box to get chin over bar',
          'Lower as SLOWLY as possible — fight gravity every centimetre',
          'Full dead hang at the bottom before the next rep',
          'The slower the negative, the more strength you build',
        ],
        research_note: 'The eccentric phase produces ~10% more strength than the concentric. Negatives are the fastest evidence-based route to a first pull-up.',
      },
      {
        id: 'band_assisted_pull_up',
        name: 'Band-assisted pull-up',
        level: 2,
        equipment: ['pullup_bar', 'bands'],
        sets: 3, reps: '6–10', rest: '2 min',
        description: 'Resistance band looped over bar reduces bodyweight. Use progressively thinner bands.',
        advance_standard: '3×8 with lightest band available',
        cues: ['Loop band around bar and place feet/knees in band', 'Do not rely on the band for momentum — let it only assist at the bottom', 'Reduce band thickness as you get stronger'],
      },
      {
        id: 'pull_up_cali',
        name: 'Pull-up',
        level: 3,
        equipment: ['pullup_bar'],
        sets: 3, reps: '3–10', rest: '2–3 min',
        description: 'Full bodyweight. The primary vertical pull exercise. Superior to lat pulldown in core activation and real-world strength transfer.',
        advance_standard: '3×10 strict with dead hang each rep',
        primary: true,
        cues: [
          'Start from DEAD HANG — arms fully extended. This lat stretch is essential',
          'Initiate by pulling shoulder blades DOWN before elbows bend',
          'Pull elbows DOWN and BACK toward hips — hands are just hooks',
          'Chin clears the bar at the top',
          'Lower SLOWLY to full dead hang — 2–3 seconds',
          'No kipping — strict reps only for hypertrophy',
        ],
        research_note: 'Harman et al. (2018): rectus abdominis was the most activated muscle in pull-ups vs all pulldown alternatives. Pull-ups create full-body tension that machines cannot replicate. Edelburg: pull-ups produce significantly greater lat activation than lat pulldowns (p < 0.05).',
      },
      {
        id: 'chin_up',
        name: 'Chin-up',
        level: 3,
        equipment: ['pullup_bar'],
        sets: 3, reps: '5–10', rest: '2–3 min',
        description: 'Underhand (supinated) grip. More bicep emphasis than pull-up, slightly easier for most people.',
        advance_standard: '3×10 strict',
        cues: ['Shoulder-width underhand grip', 'Same lat-first initiation as pull-up', 'Greater bicep activation — good variation to rotate in'],
      },
      {
        id: 'weighted_pull_up_cali',
        name: 'Weighted pull-up',
        level: 4,
        equipment: ['pullup_bar'],
        sets: 3, reps: '4–8', rest: '3–4 min',
        description: 'Add weight via vest or dip belt when bodyweight pull-ups are too easy (3×10+ with strict form).',
        advance_standard: '3×8 at +20% bodyweight',
        cues: ['Same technique as bodyweight', 'Start with 2.5–5kg', 'Dip belt is superior to vest — allows more load and cleaner movement'],
        research_note: 'Survey data: athletes who can weighted pull-up at 30–50% bodyweight typically achieve advanced tuck front lever. Weighted pulls are the single best supplementary exercise for front lever and muscle-up progress.',
      },
      {
        id: 'l_sit_pull_up',
        name: 'L-sit pull-up',
        level: 5,
        equipment: ['pullup_bar'],
        sets: 3, reps: '4–6', rest: '3 min',
        description: 'Legs held straight out at 90° throughout the pull-up. Adds extreme core demand.',
        advance_standard: '3×5 with legs held parallel to floor throughout',
        cues: ['Legs straight and together, parallel to floor', 'Pull as normal — do not let legs drop', 'This is a pull-up AND an L-sit combined'],
        research_note: 'Direct transfer to muscle-up preparation. Required strength level for strict muscle-up.',
      },
    ],
  },

  // ─── HORIZONTAL PULL (Back thickness) ─────────────────────────────────────
  back_horizontal_pull: {
    label: 'Back — Horizontal Pull',
    muscles: ['Upper back', 'Rear delts', 'Biceps', 'Rhomboids'],
    progressions: [
      {
        id: 'table_row',
        name: 'Table row / Australian pull-up',
        level: 1,
        equipment: ['bodyweight'],
        sets: 3, reps: '10–15', rest: '60 sec',
        description: 'Lie under a sturdy table or low bar. Pull chest to the surface, lower down. Body stays horizontal.',
        advance_standard: '3×15 with body fully horizontal',
        cues: ['The more horizontal your body, the harder', 'Pull chest to the bar — do not stop halfway', 'Squeeze shoulder blades together at the top'],
        research_note: 'Inverted rows produce comparable lat and upper back EMG to lat pulldowns (Edelburg). The bodyweight row is the horizontal pulling foundation for calisthenics.',
      },
      {
        id: 'inverted_row',
        name: 'Inverted row',
        level: 2,
        equipment: ['pullup_bar', 'bodyweight'],
        sets: 3, reps: '8–12', rest: '90 sec',
        description: 'Hang from a bar at chest height, body straight, pull chest to bar. Difficulty adjusted by foot position.',
        advance_standard: '3×12 with fully horizontal body',
        cues: [
          'Feet closer to bar = easier, further = harder',
          'Body in straight plank throughout — do not pike at hips',
          'Pull ELBOWS BACK AND DOWN — think about driving elbows behind you',
          'Chest touches bar at top',
          'Slow descent — 2 seconds',
        ],
      },
      {
        id: 'feet_elevated_inverted_row',
        name: 'Feet-elevated inverted row',
        level: 3,
        equipment: ['pullup_bar', 'bodyweight'],
        sets: 3, reps: '6–10', rest: '2 min',
        description: 'Feet on a bench, body fully horizontal. Closest bodyweight equivalent to a barbell row.',
        advance_standard: '3×10 with straight body',
        cues: ['Feet on bench, bar at chest height, body parallel to floor', 'Same pulling mechanics as inverted row', 'Chest contacts the bar every rep'],
      },
      {
        id: 'ring_row',
        name: 'Ring row',
        level: 3,
        equipment: ['bodyweight'],
        sets: 3, reps: '8–12', rest: '2 min',
        description: 'Gymnastic rings allow a natural grip rotation — reduces elbow stress. Rings move toward body as you pull, mimicking cable row.',
        advance_standard: '3×12 with fully horizontal body',
        cues: ['Rings at waist height for harder version, higher for easier', 'Rings can rotate — let them follow your natural wrist path', 'Pull rings to lower chest'],
      },
    ],
  },

  // ─── SQUAT PATTERN (Legs) ──────────────────────────────────────────────────
  squat_pattern: {
    label: 'Legs — Squat / Quad Dominant',
    muscles: ['Quads', 'Glutes', 'Core'],
    honest_note: 'This is the limitation of pure calisthenics: bodyweight squats plateau quickly. The jump from bodyweight squat to pistol squat is large and takes months. If adding a weight vest or progressing to barbell is possible, do it — your legs will grow faster. Calisthenics is exceptional for upper body; legs benefit more from load.',
    progressions: [
      {
        id: 'bodyweight_squat',
        name: 'Bodyweight squat',
        level: 1,
        equipment: ['bodyweight'],
        sets: 3, reps: '15–25', rest: '60 sec',
        description: 'The foundation. Full depth — hip crease below knee. If this is too easy, move on immediately.',
        advance_standard: '3×25 with full depth, straight back',
        cues: ['Feet shoulder-width, toes out 15–30°', 'Hip crease BELOW knee — no quarter squats', 'Keep chest up, weight over mid-foot'],
      },
      {
        id: 'jump_squat',
        name: 'Jump squat',
        level: 2,
        equipment: ['bodyweight'],
        sets: 3, reps: '10–15', rest: '90 sec',
        description: 'Explosive squat, jump at the top. Develops power and keeps quad stimulus higher than standard squat.',
        advance_standard: '3×15 with full squat depth before jump',
        cues: ['Squat to depth, then explode upward', 'Land softly — full foot, absorb through the hips', 'Reset to full depth before the next rep'],
      },
      {
        id: 'bulgarian_split_squat',
        name: 'Bulgarian split squat',
        level: 3,
        equipment: ['bodyweight'],
        sets: 3, reps: '8–12 each leg', rest: '2 min',
        description: 'Rear foot elevated on a bench, front foot forward. The best single-leg bodyweight quad exercise — high enough difficulty to actually stimulate muscle growth.',
        advance_standard: '3×12 each leg with rear knee near floor',
        cues: [
          'Rear foot on bench behind you, front foot far enough forward to stay upright',
          'Lower rear knee toward floor — hip crease well below front knee',
          'Keep front shin relatively vertical — weight over mid-foot',
          'This exercise should be HARD. If not, add weight or progress to pistol squat',
        ],
        research_note: 'The Bulgarian split squat is the closest bodyweight exercise to a loaded squat in terms of quad stimulus. At bodyweight, it is significantly harder than a standard squat due to the stability and range of motion demands.',
      },
      {
        id: 'shrimp_squat',
        name: 'Shrimp squat',
        level: 4,
        equipment: ['bodyweight'],
        sets: 3, reps: '5–8 each leg', rest: '2–3 min',
        description: 'Single-leg squat with rear leg held behind you. Harder than pistol for many people due to hip flexor demand.',
        advance_standard: '3×6 each leg with rear knee touching floor',
        cues: ['Hold rear foot behind you', 'Lower slowly until rear knee grazes floor', 'Push through heel of front foot to stand'],
      },
      {
        id: 'pistol_squat',
        name: 'Pistol squat',
        level: 5,
        equipment: ['bodyweight'],
        sets: 3, reps: '3–8 each leg', rest: '3 min',
        description: 'Single-leg squat with the other leg extended forward. The pinnacle of bodyweight leg training. Requires strength, balance, and ankle/hip mobility.',
        advance_standard: '3×5 each leg with full depth',
        prerequisite: 'Must have adequate ankle dorsiflexion and hip mobility. If mobility is the limiting factor, address that first.',
        cues: [
          'Non-working leg extends straight in front — parallel to floor',
          'Lower all the way to full depth — hips below knee',
          'Arms out for counterbalance',
          'Push through heel to stand',
          'If limited by mobility, elevate heel or use a pole for balance assistance temporarily',
        ],
      },
      {
        id: 'weighted_vest_squat',
        name: 'Weighted squat (vest)',
        level: 4,
        equipment: ['bodyweight'],
        sets: 3, reps: '8–12', rest: '2–3 min',
        description: 'Any squat variation with a weighted vest. Bridges the progression gap and makes bodyweight squatting significantly more effective for hypertrophy.',
        advance_standard: 'Progress weight in vest',
        cues: ['Same technique as bodyweight squat', 'Start with 5–10% bodyweight in vest', 'Progress in the same way as barbell — add weight when reps feel easy'],
        research_note: 'Adding a weighted vest is the single most effective way to address the leg stimulus limitation of calisthenics. Honest recommendation: if you want significant leg growth, add load.',
      },
    ],
  },

  // ─── HIP HINGE (Posterior chain) ──────────────────────────────────────────
  hip_hinge: {
    label: 'Posterior Chain — Hip Hinge',
    muscles: ['Hamstrings', 'Glutes', 'Lower back'],
    honest_note: 'Hip hinge is the hardest pattern to train effectively with pure bodyweight. Nordic curls and single-leg RDLs are excellent but peak out in difficulty without load. A kettlebell or dumbbell is highly recommended for this pattern.',
    progressions: [
      {
        id: 'glute_bridge',
        name: 'Glute bridge',
        level: 1,
        equipment: ['bodyweight'],
        sets: 3, reps: '15–20', rest: '60 sec',
        description: 'Lie on back, feet flat, drive hips up. Foundation glute activator.',
        advance_standard: '3×20 with full hip extension',
        cues: ['Drive hips UP until straight — do not stop halfway', 'Squeeze glutes hard at the top', 'Feet flat, shins vertical'],
      },
      {
        id: 'hip_thrust_bodyweight',
        name: 'Hip thrust (bodyweight)',
        level: 2,
        equipment: ['bodyweight'],
        sets: 3, reps: '12–20', rest: '90 sec',
        description: 'Shoulders on a bench, feet on floor, drive hips up. More range than glute bridge.',
        advance_standard: '3×20 with full lockout',
        cues: ['Upper back on bench, feet hip-width', 'Drive hips UP until body forms a straight line from shoulders to knees', 'Squeeze glutes at top, hold 1 second'],
      },
      {
        id: 'single_leg_glute_bridge',
        name: 'Single-leg glute bridge',
        level: 2,
        equipment: ['bodyweight'],
        sets: 3, reps: '10–15 each side', rest: '90 sec',
        description: 'Same as glute bridge but one leg extended. Significantly harder.',
        advance_standard: '3×12 each side with full extension',
        cues: ['Non-working leg straight in air or on a bench', 'Drive hip up through the working leg only', 'Do not let non-working hip drop'],
      },
      {
        id: 'nordic_curl',
        name: 'Nordic curl',
        level: 4,
        equipment: ['bodyweight'],
        sets: 3, reps: '3–8', rest: '3 min',
        description: 'Kneel, secure feet under a heavy surface, lower your body forward as slowly as possible. One of the highest-intensity hamstring exercises in existence.',
        advance_standard: '3×5 with 4+ second descent',
        prerequisite: 'Must have good hamstring flexibility and no knee issues',
        cues: [
          'Kneel with feet secured under something heavy (sofa, radiator, partner)',
          'Body is straight from knees to head',
          'Lower forward as SLOWLY as possible — fight the whole way down',
          'At the bottom, push with hands to save yourself',
          'Pull back up with hamstrings — this is the hardest part',
        ],
        research_note: 'Nordic curls produce among the highest hamstring activation of any exercise (EMG research). Training hamstrings at long length (fully extended position during nordic) produces superior hypertrophy consistent with stretch-position loading research (Maeo et al. 2023).',
      },
      {
        id: 'single_leg_rdl_bodyweight',
        name: 'Single-leg RDL (bodyweight)',
        level: 3,
        equipment: ['bodyweight'],
        sets: 3, reps: '10–12 each side', rest: '2 min',
        description: 'Hinge forward on one leg, extend the other behind you. Good hamstring and hip control exercise.',
        advance_standard: '3×12 each side with hands reaching toward floor',
        cues: [
          'Soft knee on standing leg',
          'Hinge at hip — back stays FLAT, do not round',
          'Non-working leg extends behind you as a counterbalance',
          'Reach hands toward floor to extend range of motion',
          'Feel the hamstring stretch at the bottom',
        ],
      },
    ],
  },

  // ─── CORE — Anti-extension ─────────────────────────────────────────────────
  core: {
    label: 'Core — Anti-extension',
    muscles: ['Abs', 'Obliques', 'Hip flexors'],
    progressions: [
      {
        id: 'plank',
        name: 'Plank',
        level: 1,
        equipment: ['bodyweight'],
        sets: 3, reps: '30–60 sec', rest: '60 sec',
        description: 'The baseline anti-extension core exercise.',
        advance_standard: '3×60 sec with no hip sag',
        cues: ['Straight line from head to heels', 'Do not let hips sag or pike up', 'Breathe normally — do not hold breath'],
      },
      {
        id: 'hollow_body_hold',
        name: 'Hollow body hold',
        level: 2,
        equipment: ['bodyweight'],
        sets: 3, reps: '20–45 sec', rest: '90 sec',
        description: 'Lie on back, press lower back into floor, arms and legs extended. The foundation of all gymnastics and calisthenics positions.',
        advance_standard: '3×45 sec with back fully flat',
        cues: [
          'Press your lower back INTO the floor — no gap',
          'Arms extended overhead, legs extended and lifted',
          'The lower your legs, the harder — keep them as low as you can while maintaining back contact',
          'This body position appears in planche, front lever, handstand, muscle-up',
        ],
        research_note: 'The hollow body is the fundamental tension position for all calisthenics skills. Developing this hold accelerates every skill.',
      },
      {
        id: 'leg_raise',
        name: 'Hanging leg raise',
        level: 3,
        equipment: ['pullup_bar'],
        sets: 3, reps: '8–15', rest: '90 sec',
        description: 'Hang from a bar, raise straight legs to parallel or above. Hip flexor and lower ab dominant.',
        advance_standard: '3×12 with straight legs and controlled descent',
        cues: ['No kipping — dead stop at the bottom', 'Toes to bar at advanced level', 'Lower slowly — the eccentric is where the work happens'],
      },
      {
        id: 'l_sit',
        name: 'L-sit',
        level: 4,
        equipment: ['bodyweight'],
        sets: 3, reps: '5–15 sec holds', rest: '2 min',
        description: 'Support body on hands (floor, parallettes, or bars), legs straight out at 90°. A fundamental gymnastics strength position.',
        advance_standard: '3×15 sec hold on parallettes',
        prerequisite: 'Tuck L-sit (knees bent) should be mastered first',
        cues: [
          'Hands directly under hips',
          'Depress and protract shoulders — push the floor away',
          'Legs straight, parallel to floor — toes pointed',
          'Start with tuck L-sit (knees to chest) and extend one leg at a time',
        ],
        research_note: 'L-sit directly builds the hip flexor and core compression strength needed for front lever, planche, and muscle-up transitions.',
      },
      {
        id: 'dragon_flag',
        name: 'Dragon flag',
        level: 5,
        equipment: ['bodyweight'],
        sets: 3, reps: '4–8', rest: '3 min',
        description: 'Lie on a bench, hold edge behind head, raise and lower body in a rigid plank position. Extreme total body tension.',
        advance_standard: '3×6 with full extension',
        cues: [
          'Hold the bench firmly behind your head — anchors you',
          'Keep body COMPLETELY straight from shoulders to toes',
          'Lower slowly — the eccentric is the work',
          'Start with tuck dragon flag (knees bent) and progress to straight legs',
        ],
        research_note: 'Dragon flag develops the specific anti-extension core strength that transfers to front lever. The body position is nearly identical.',
      },
    ],
  },
};

// ─── SKILL PROGRESSION LADDERS ────────────────────────────────────────────────
// These are the advanced skill progressions shown in the Calisthenics tab.
// Each step has hold/rep standards that must be achieved before advancing.
// Based on publicly available methodology — not copied from any paid program.

export const SKILL_PROGRESSIONS = {

  planche: {
    id: 'planche',
    name: 'Planche',
    category: 'push',
    description: 'Hold your entire body horizontal above the ground on straight arms. A B-level gymnastics skill. Requires extraordinary anterior deltoid, chest, and core strength.',
    muscles: ['Anterior deltoids', 'Chest', 'Triceps', 'Serratus anterior', 'Core'],
    equipment_needed: ['bodyweight'],
    equipment_recommended: ['bodyweight'],
    typical_timeline: '1–4 years of consistent training',
    training_frequency: '3–4× per week. Not same session as heavy pressing.',
    key_principle: 'The planche is a lever exercise. Increasing torque progressively from ~113 Nm (tuck) to ~183 Nm (full) is the progression logic.',
    wrist_warning: 'Wrist conditioning is mandatory before starting planche training. Do daily wrist circles, push-ups on fists, and parallette holds. Skip this and you will get injured.',
    steps: [
      {
        id: 'planche_lean',
        name: 'Planche lean',
        step: 1,
        description: 'In a push-up position, shift your bodyweight forward over your hands by leaning. Hands point forward or slightly rotated out. Hold the forward position.',
        hold_standard: '3×30 sec with significant forward lean',
        sets: 4, hold_secs: 10, rest: '2 min',
        cues: [
          'Hands rotated slightly outward',
          'Lean body weight FORWARD over hands — shoulders should be in front of hands',
          'The more forward your lean, the more planche-specific the stimulus',
          'Protract (push out) and depress (pull down) shoulder blades',
          'Keep body rigid — hollow body position throughout',
        ],
        supplementary: ['Pseudo planche push-ups', 'Wrist conditioning'],
      },
      {
        id: 'tuck_planche',
        name: 'Tuck planche',
        step: 2,
        description: 'Knees tucked to chest, body horizontal, arms straight. Your feet are off the ground. Shoulder torque ~113 Nm.',
        hold_standard: '3×10 sec holds',
        sets: 4, hold_secs: 5, rest: '2–3 min',
        cues: [
          'Tuck knees TIGHT to chest',
          'Round upper back slightly — this is correct form for tuck planche',
          'Push the ground AWAY — protract and depress scapulae hard',
          'Hips and shoulders should be roughly level — body parallel to ground',
          'Use parallettes to reduce wrist strain',
        ],
        supplementary: ['Planche leans', 'Pseudo planche push-ups', 'Band-assisted tuck holds'],
      },
      {
        id: 'advanced_tuck_planche',
        name: 'Advanced tuck planche',
        step: 3,
        description: 'Hips extended back, knees still bent at ~90°, back parallel to ground. Significantly harder than tuck. Shoulder torque ~136 Nm.',
        hold_standard: '3×10 sec holds',
        sets: 4, hold_secs: 5, rest: '2–3 min',
        cues: [
          'Extend hips BACK from the tuck position',
          'Back must be FLAT and parallel to ground — not tilted',
          'Knees are bent but hips are open',
          'This is the critical skill junction — many people plateau here for months',
          'Supplementary: planche push-ups in tuck position + weighted pseudo planche push-ups',
        ],
        supplementary: ['Tuck planche push-ups', 'Weighted pseudo planche push-ups', 'Band-assisted advanced tuck'],
      },
      {
        id: 'straddle_planche',
        name: 'Straddle planche',
        step: 4,
        description: 'Both legs extended straight, spread wide. The wider the straddle, the easier. Shoulder torque ~162 Nm.',
        hold_standard: '3×5 sec holds',
        sets: 4, hold_secs: 3, rest: '3 min',
        cues: [
          'From advanced tuck, extend legs out to the sides',
          'The WIDER your straddle, the easier — start very wide',
          'Slowly bring legs together over time as you get stronger',
          'Body fully parallel to ground',
          'Arms straight, scapulae protracted and depressed',
        ],
        supplementary: ['Advanced tuck push-ups', 'Straddle planche leans', 'Weighted vest pseudo planche push-ups'],
      },
      {
        id: 'half_lay_planche',
        name: 'Half-lay planche',
        step: 5,
        description: 'Legs at less than full straddle width — narrowing from straddle toward full. Optional intermediate step.',
        hold_standard: '3×3 sec holds',
        sets: 4, hold_secs: 2, rest: '3 min',
        cues: ['Between straddle and full — legs narrower than straddle but not together', 'Keep body fully parallel to ground', 'Every cm the legs come together increases the demand significantly'],
        supplementary: ['Straddle push-ups', 'Straddle planche leans with legs narrowing'],
      },
      {
        id: 'full_planche',
        name: 'Full planche',
        step: 6,
        description: 'Both legs fully extended, together, body completely horizontal. Shoulder torque ~183 Nm. B-level gymnastics skill on floor, C-level on rings.',
        hold_standard: '5 sec clean hold',
        sets: 5, hold_secs: 3, rest: '4 min',
        cues: [
          'Legs fully extended, together',
          'Entire body parallel to the ground',
          'Scapulae maximally protracted and depressed',
          'Hollow body — abs and glutes squeezed',
          'Arms completely straight',
        ],
      },
    ],
  },

  front_lever: {
    id: 'front_lever',
    name: 'Front lever',
    category: 'pull',
    description: 'Hang from a bar with your body horizontal, parallel to the ground, arms straight. The pulling counterpart to the planche. Primarily a lat and core exercise.',
    muscles: ['Lats', 'Core (abs, obliques)', 'Rear delts', 'Rhomboids', 'Glutes'],
    equipment_needed: ['pullup_bar'],
    equipment_recommended: ['pullup_bar'],
    typical_timeline: '6 months to 3 years depending on bodyweight and training history',
    training_frequency: '3–4× per week. Not same session as heavy pulling.',
    key_principle: 'The front lever is a pulling exercise. Pull the bar DOWN toward your hips throughout — this engages the lats correctly. Half-step progressions between main steps dramatically smooth progress.',
    steps: [
      {
        id: 'inverted_hang',
        name: 'Inverted hang',
        step: 1,
        description: 'Hang from bar with body inverted, fully tucked. Builds initial strength and comfort in the inverted position.',
        hold_standard: '3×30 sec',
        sets: 3, hold_secs: 15, rest: '90 sec',
        cues: ['Hang upside down, body tucked tightly', 'Arms straight', 'Pull shoulder blades down — active not passive hang'],
      },
      {
        id: 'tuck_front_lever',
        name: 'Tuck front lever',
        step: 2,
        description: 'Knees pulled to chest, hips level with shoulders, body parallel to ground. The first real front lever position.',
        hold_standard: '3×15 sec holds',
        sets: 4, hold_secs: 8, rest: '2 min',
        cues: [
          'Pull knees TIGHT to chest',
          'Hips must be level with shoulders — not drooping',
          'Think: pull the bar DOWN toward your hips throughout',
          'Body parallel to ground',
          'Squeeze glutes and abs hard',
        ],
        supplementary: ['Tuck front lever rows (dynamic version)', 'Dragon flag', 'Weighted pull-ups'],
      },
      {
        id: 'advanced_tuck_front_lever',
        name: 'Advanced tuck front lever',
        step: 3,
        description: 'Hips open to ~90° angle, knees stacked directly over hips, back flat. The key transition step.',
        hold_standard: '3×10 sec holds',
        sets: 4, hold_secs: 6, rest: '2–3 min',
        cues: [
          'Open hips from tuck position — thighs roughly perpendicular to torso',
          'Back must be FLAT — not rounded as in tuck',
          'Knees stacked above hips',
          'Hips and shoulders still level — body parallel to ground',
        ],
        half_step: 'One-legged advanced tuck: one leg extended, one tucked. Do this between tuck and advanced tuck for smoother progression.',
        supplementary: ['Advanced tuck front lever rows', 'Dragon flags', 'Weighted pull-ups'],
      },
      {
        id: 'one_leg_front_lever',
        name: 'One-leg front lever',
        step: 4,
        description: 'One leg fully extended in line with the body, one leg tucked. Alternate sides every set.',
        hold_standard: '3×8 sec each side',
        sets: 4, hold_secs: 5, rest: '2–3 min',
        cues: [
          'One leg straight — perfectly in line with hips and torso',
          'Other leg tucked to chest',
          'Alternate sides — develop both equally',
          'The closer the tucked leg to the body, the easier',
        ],
        supplementary: ['One-leg front lever rows', 'Weighted pull-ups'],
      },
      {
        id: 'straddle_front_lever',
        name: 'Straddle front lever',
        step: 5,
        description: 'Both legs straight, spread wide in a V-shape. Wider = easier. Narrow straddle over time.',
        hold_standard: '3×5 sec holds',
        sets: 4, hold_secs: 3, rest: '3 min',
        cues: [
          'Both legs straight and extended wide',
          'Start with the widest straddle you can manage',
          'Slowly bring legs together over time as strength increases',
          'Body parallel to ground throughout',
        ],
        half_step: 'One-legged straddle: one leg straight out, one leg bent. Smoother step between one-leg and full straddle.',
        supplementary: ['Straddle front lever rows', 'Ice cream makers', 'Weighted pull-ups at 30–50% bodyweight'],
      },
      {
        id: 'full_front_lever',
        name: 'Full front lever',
        step: 6,
        description: 'Both legs fully extended, together. Body perfectly horizontal, arms straight. Maximum strength required.',
        hold_standard: '5 sec clean hold',
        sets: 5, hold_secs: 3, rest: '4 min',
        cues: [
          'Both legs together, fully extended',
          'Body perfectly parallel to ground',
          'Arms completely straight — not bent at the elbow',
          'Pull bar DOWN toward hips throughout',
          'Hollow body tension — abs, glutes, quads all squeezed',
        ],
      },
    ],
  },

  muscle_up: {
    id: 'muscle_up',
    name: 'Muscle-up',
    category: 'compound',
    description: 'Pull your entire body from hanging below the bar to support above it. Three phases: pull (lats, biceps), transition (technique), press (triceps, chest). The most common first advanced calisthenics skill.',
    muscles: ['Lats', 'Biceps', 'Triceps', 'Chest', 'Core', 'Forearms'],
    equipment_needed: ['pullup_bar'],
    equipment_recommended: ['pullup_bar'],
    typical_timeline: '2–6 months from a solid pull-up base',
    training_frequency: '2–3× per week — requires full recovery.',
    prerequisites_hard: [
      '10 strict chest-to-bar pull-ups',
      '10 straight-bar dips',
      '30-second false grip hang',
    ],
    key_principle: 'The transition is where 90% of people fail. It is a technique problem, not a strength problem. Practice the transition separately as a drill.',
    steps: [
      {
        id: 'false_grip_hang',
        name: 'False grip hang',
        step: 1,
        description: 'Grip the bar with your wrist over it rather than wrapping your hand around it. Hold this position. Builds the wrist strength needed for the transition.',
        hold_standard: '3×30 sec',
        sets: 3, hold_secs: 15, rest: '90 sec',
        cues: [
          'Place the bar in the bend of your wrist — not in your palm',
          'Make a tight fist',
          'This grip shortens the range of motion for the transition',
          'It will be uncomfortable at first — this is normal',
        ],
      },
      {
        id: 'chest_to_bar_pull_up',
        name: 'Chest-to-bar pull-up',
        step: 2,
        description: 'Pull until your sternum (not just chin) touches the bar. Builds the high pulling strength needed for the transition.',
        hold_standard: '3×8 strict reps',
        sets: 4, reps: '5–8', rest: '2–3 min',
        cues: [
          'Pull until your CHEST touches the bar — not just chin',
          'Elbows travel back behind your torso at the top',
          'This is significantly harder than a standard pull-up',
          'Use false grip when training these for muscle-up carryover',
        ],
      },
      {
        id: 'transition_drill',
        name: 'Transition drill',
        step: 3,
        description: 'The most important step. Start with chest at bar level, practice rotating wrists over and dipping into the support position.',
        hold_standard: 'Smooth, controlled transitions — aim for 5 per session',
        sets: 5, reps: '3–5', rest: '2 min',
        cues: [
          'Jump or use a box to get chest to bar level',
          'From this position, rotate your wrists over and lean your chest forward',
          'Your elbows should end up pointing BEHIND you, not out to the sides',
          'Practice this slow and controlled before attempting speed',
          'This wrist rotation and forward lean is the entire technique of the muscle-up',
        ],
      },
      {
        id: 'negative_muscle_up',
        name: 'Negative muscle-up',
        step: 4,
        description: 'Start in the top support position (above the bar). Lower through the transition slowly to a dead hang. Build eccentric strength through the full range.',
        hold_standard: '3×5 with 4+ second descent',
        sets: 4, reps: '3–5', rest: '3 min',
        cues: [
          'Jump or step to support position (elbows locked out, body above bar)',
          'Lower through the dip slowly',
          'At the transition point, go as slowly as possible',
          'Continue to dead hang',
          'The slower you go, the more strength you build in the transition',
        ],
      },
      {
        id: 'kipping_muscle_up',
        name: 'Kipping muscle-up',
        step: 5,
        description: 'Use momentum from a swing to assist getting over the bar. A valid first muscle-up — reduce kip over time as strength develops.',
        hold_standard: '3 controlled reps',
        sets: 3, reps: '2–3', rest: '3 min',
        cues: [
          'Swing forward in a hollow body position',
          'As your body swings back, pull explosively and lean chest forward',
          'Use just enough kip to get over — do not swing wildly',
          'Goal is to reduce kip progressively until it is strict',
        ],
      },
      {
        id: 'strict_muscle_up',
        name: 'Strict muscle-up',
        step: 6,
        description: 'No swing, no kip. Pure strength from dead hang to support. The final form.',
        hold_standard: '3 strict reps',
        sets: 3, reps: '1–5', rest: '4 min',
        cues: [
          'Start from dead hang, no swing',
          'Pull explosively with false grip — elbows drive behind you',
          'Rotate wrists over at the transition',
          'Press to lockout',
          'If you need a kip, you are not yet strong enough — build more chest-to-bar strength',
        ],
      },
    ],
  },

  handstand: {
    id: 'handstand',
    name: 'Handstand',
    category: 'push',
    description: 'Support your entire body vertically on your hands. Primarily a SKILL — balance and proprioception matter as much as strength. Needs daily dedicated practice, not just sets in a workout.',
    muscles: ['Shoulders (all heads)', 'Triceps', 'Upper traps', 'Serratus anterior', 'Core', 'Wrists'],
    equipment_needed: ['bodyweight'],
    equipment_recommended: ['bodyweight'],
    typical_timeline: 'Wall handstand: 2–4 weeks. Freestanding 10 sec: 3–12 months. Freestanding consistent: 6 months–2 years.',
    training_frequency: '4–6× per week. Daily practice is the accelerator. Short frequent sessions beat long infrequent ones.',
    key_principle: 'The handstand is a skill first. 20–30 freestanding attempts per session, 4× per week beats 1 long session weekly. Neural adaptation requires frequency.',
    wrist_warning: 'Wrist conditioning daily before any handstand training. Circles, compressions, push-ups on fists.',
    steps: [
      {
        id: 'wrist_prep',
        name: 'Wrist conditioning',
        step: 1,
        description: 'Daily routine to prepare wrists for inverted loading. Non-negotiable prerequisite.',
        hold_standard: 'Daily — 5 minutes before any handstand work',
        sets: 1, reps: 'Daily routine', rest: 'N/A',
        cues: [
          'Wrist circles both directions — 10 each',
          'Kneel on floor, place hands flat, rock weight forward gently',
          'Push-ups on fists — avoids wrist extension under load',
          'Do this every single session before handstands',
        ],
      },
      {
        id: 'crow_stand',
        name: 'Crow stand',
        step: 2,
        description: 'Knees resting on the backs of your arms (bent arms). Balance exposure without full inversion — the first balance skill.',
        hold_standard: '3×10 sec holds',
        sets: 4, hold_secs: 5, rest: '90 sec',
        cues: [
          'Squat down, hands on floor, knees rest on the backs of your upper arms',
          'Lean forward until feet lift off — find the balance point',
          'Bent arms only — this is NOT a planche',
          'Look forward at the floor, not down',
        ],
      },
      {
        id: 'pike_push_up_hs',
        name: 'Pike push-up (HSPU prep)',
        step: 2,
        equipment: ['bodyweight'],
        description: 'Builds the shoulder pressing strength needed for handstand push-ups.',
        hold_standard: '3×10 strict reps, head near to floor',
        sets: 3, reps: '8–12', rest: '2 min',
        cues: ['Hips as high as possible, inverted V', 'Head lowers BETWEEN hands', 'Full range — do not stop halfway'],
      },
      {
        id: 'wall_walk',
        name: 'Wall walk',
        step: 3,
        description: 'Start in a plank with feet at the wall, walk your feet up the wall while walking your hands toward the wall. Build shoulder strength and inversion familiarity.',
        hold_standard: '5 smooth wall walks',
        sets: 3, reps: '3–5', rest: '2 min',
        cues: [
          'Start in plank, feet against the wall',
          'Walk feet UP the wall while hands walk TOWARD the wall',
          'Get as vertical as you can without falling',
          'Walk back down controlled',
        ],
      },
      {
        id: 'back_to_wall_handstand',
        name: 'Back-to-wall handstand',
        step: 4,
        description: 'Kick up with your back to the wall. Hold for time. Builds strength and basic inversion confidence. Less ideal for alignment than chest-to-wall.',
        hold_standard: '3×60 sec',
        sets: 3, hold_secs: 30, rest: '2 min',
        cues: [
          'Stand with back to wall, place hands on floor near wall',
          'Kick up to handstand, back touches wall',
          'Arms straight, body as straight as possible',
          'Use wall only as safety — try to hold balance',
        ],
      },
      {
        id: 'chest_to_wall_handstand',
        name: 'Chest-to-wall handstand',
        step: 5,
        description: 'Face the wall, walk hands up until vertical. Better alignment than back-to-wall — forces straight body line.',
        hold_standard: '3×30 sec with straight body',
        sets: 4, hold_secs: 20, rest: '2 min',
        cues: [
          'Face the wall, hands close to wall',
          'Walk feet up wall until fully inverted',
          'Body should form a STRAIGHT line — use a mirror or film yourself',
          'No banana back — hips must stay over hands',
          'Shoulders actively pushing floor away',
        ],
      },
      {
        id: 'shoulder_taps',
        name: 'Shoulder taps (handstand)',
        step: 6,
        description: 'In a wall handstand, shift weight to one arm and tap the opposite shoulder with the free hand. Builds single-arm balance.',
        hold_standard: '10 taps each side without losing the wall',
        sets: 3, reps: '5–10 each side', rest: '2 min',
        cues: [
          'Start in chest-to-wall handstand',
          'Shift ALL weight to one arm',
          'Tap the opposite shoulder quickly',
          'Return to two arms',
          'Get comfortable with single-arm weight before freestanding',
        ],
      },
      {
        id: 'freestanding_kick_up',
        name: 'Kick-up practice',
        step: 7,
        description: 'Practice controlled entries into freestanding handstand. The entry and exit are skills in themselves. Learn to bail safely first.',
        hold_standard: 'Consistent entries — 20–30 attempts per session',
        sets: 1, reps: '20–30 attempts', rest: '10–15 sec between',
        cues: [
          'One foot steps forward, the other kicks up — ONE kick only (double kick = less control)',
          'Look at a fixed point on the floor between your hands',
          'Arms straight, wrists over shoulders, hips over wrists',
          'Practice falling safely — cartwheel out or pirouette forward',
          'Volume and frequency are the only variables that matter here — just do more attempts',
        ],
        key_note: '20–30 attempts per session, 4× per week. This is non-negotiable for freestanding progress. One attempt per session will not work.',
      },
      {
        id: 'freestanding_handstand',
        name: 'Freestanding handstand',
        step: 8,
        description: 'Hold a freestanding handstand for increasing duration. The goal.',
        hold_standard: '10 sec consistent → 30 sec consistent',
        sets: 5, hold_secs: 5, rest: '1 min',
        cues: [
          'Find balance through FINGERS — press them into the ground to counterbalance falling forward',
          'Slight hollow body — do not arch your back (banana handstand)',
          'Eyes fixed on a spot between your hands',
          'Breathe normally — holding breath tenses everything',
          'The balance point is a moving target — constantly adjust',
        ],
      },
    ],
  },
};

// ─── SESSION STRUCTURE ─────────────────────────────────────────────────────────
// How to combine skill work and volume work in the same session.
// Skill first (fresh CNS), volume second. Universally agreed across all credible coaching.

export const SESSION_STRUCTURE = {

  pure_calisthenics: {
    label: 'Pure calisthenics session',
    description: 'Skill block first, then volume. Never fatigue yourself before skill practice.',
    blocks: [
      {
        name: 'Warm-up',
        duration_min: 5,
        content: 'Wrist conditioning, shoulder mobility, hollow body holds, scapular pull-ups. Not optional — wrists and shoulders must be prepared before any skill or volume work.',
      },
      {
        name: 'Skill block',
        duration_min: 15,
        content: 'Current skill progression step. 40–60% max effort per set. Never to failure. Stop when form degrades. Quality over quantity.',
        principle: 'Greasing the groove within the session — frequent high-quality exposures.',
        note: 'If working toward multiple skills (e.g. handstand + front lever), do the one requiring the most freshness first.',
      },
      {
        name: 'Volume block',
        duration_min: 35,
        content: 'Progressive overload work. Current variation level, 3–5 sets, last set approaching failure. This is where hypertrophy and strength volume accumulates.',
        overload_mechanism: 'Harder variation → more reps at current variation → more sets → slower tempo → weighted vest/belt',
      },
    ],
  },

  hybrid: {
    label: 'Hybrid session (gym + calisthenics)',
    description: 'Skill block at the start. Calisthenics and gym exercises interchangeable within the volume block — same movement pattern, different tools.',
    blocks: [
      {
        name: 'Warm-up',
        duration_min: 5,
        content: 'Same as pure calisthenics warm-up.',
      },
      {
        name: 'Skill block',
        duration_min: 10,
        content: 'Skill practice before any fatiguing work. Even 2–3 sets of planche leans or handstand kick-ups counts.',
      },
      {
        name: 'Volume block',
        duration_min: 40,
        content: 'Mix of gym exercises and calisthenics as appropriate. Pull-ups as primary over lat pulldowns. Dips alongside or instead of machine press. Bodyweight progressions as primary or accessory.',
      },
    ],
  },

  gtg_mode: {
    label: 'Greasing the groove (skill acceleration)',
    description: 'Not a standard session — a day-long practice method for rapid skill development. Coined by Pavel Tsatsouline (The Naked Warrior, 2003). Validated by frequency research (Häkkinen et al. 1988).',
    rules: [
      'Never train the skill to failure',
      'Sets are 40–60% of your current maximum',
      'Minimum 15–30 minutes between sets',
      'Perfect form on every single rep — you are building a neural pathway',
      'Volume accumulates throughout the day across 5–10 mini-sets',
      'Works best for: pull-ups, push-ups, dips, and static holds (planche, front lever, handstand)',
    ],
    example: 'Max pull-ups = 8. GTG: do 4 pull-ups every hour for 8 hours = 32 total reps with perfect form. Compare to 3×8 = 24 reps with fatigue-compromised later reps.',
    research: 'Häkkinen et al. (1988): distributing training volume across multiple sessions improved neuromuscular adaptations vs single-session training. Zatsiorsky & Kraemer (2006): strength is a skill — neural efficiency improves with frequent quality practice.',
  },
};

// ─── LEGS HONEST ASSESSMENT ───────────────────────────────────────────────────

export const LEGS_HONEST_NOTE = {
  title: 'Honest note on calisthenics legs',
  message: "Calisthenics is exceptional for upper body development. For lower body, the progression caps are real: bodyweight squats become easy quickly, and the jump to pistol squats is large and requires significant mobility work. Your legs are your body's strongest muscles — they need load to grow meaningfully. If you are doing pure calisthenics, these options keep legs progressing: (1) Bulgarian split squats and single-leg variations, which are genuinely difficult; (2) Nordic curls for hamstrings, which produce extreme stimulus; (3) a weighted vest for any squat variation; or (4) adding a single barbell/dumbbell leg session to your week. Option 4 will produce the best results. This is not a limitation of the app — it is honest programming.",
  recommended_additions: [
    'Weighted vest for squat variations',
    'Nordic curls (no equipment, maximum hamstring stimulus)',
    'Single barbell/dumbbell leg session weekly',
  ],
};
